### ISSUE TITLE
tab switching does not show "Show all tabs" button consistently

### ISSUE THREAD

**Issue by stevehav** [ghostery/user-agent-desktop#565]
I've opened enough tabs to have the alt-tab tab switcher not show all available tabs (I can switch among the last 6 or 7, where I have maybe 15 open), and sometimes the "Show all tabs" button appears underneath the tabs list, while sometimes it doesn't. This impairs keyboard-based browser use -- I have to click the desired tab with the mouse instead. I haven't been able to figure out the conditions for whether it appears or not and will update this if/when I do.

**Comment by chrmod** [comment]
@stevehav thanks for the report. Can you please try to test on the latest release `2021.07.3`. We've made some theme fixes and maybe this issue is already resolved. If not can you please post a screen shot?

**Comment by stevehav** [comment]
Hi @chrmod, thanks so much for the heads-up. I upgraded, and still have the same issue. I'll attach a screenshot...

Just to recap, in this screenshot there are around 14 or 15 tabs, including 2 pinned tabs, open on the browser. When I use ctrl-tab to switch among the tabs, it only shows those seven tabs in the switcher, and even if I hit tab repeatedly to cycle the selection through those seven, it never shows me the others. It doesn't scroll through the full tab list at all, so the only way I could access the rest would be by clicking with the mouse.

![IMG_3481](https://user-images.githubusercontent.com/7684093/129993367-55e42426-3dfd-42ee-8c6a-e8a8a6b06f63.jpeg)

**Comment by chrmod** [comment]
Hi @stevehav - now I finally got it. Looks like you are using tab switcher that orders tabs by the time they were recently used. 
I believe this is an intended behavior of this feature. 

This article explains how you can disable it:
https://winaero.com/disable-ctrltab-thumbnail-previews-firefox/

If you still think there is some problem there, please try to test it in vanilla Firefox. If the behavior is the same there, you should report a bug directly to Mozilla https://bugzilla.mozilla.org/

**Comment by chrmod** [comment]
I'm closing the issue as there is no much we can do about it if we dont want to change Firefox default behavior
